export default function generator(){
    //Elegiremos el sexo del trabajador sacando un numero aleatorio entre 1 y 10
    var chooseSex = Math.floor(Math.random()*10)
    let sex = ''
    if(chooseSex <= 5){
        sex = 'M'
    }else {
        sex = 'F'
    }
    if (sex == 'M'){
	var firstname = ["Adrián", "Charles", "Alberto", "Alexander","Paco", "Alexis", "Alonso", "Pope", "Ángel", "Anthony", "Antonio", "James", "Christian", "Tomen", "Carlos", "Robert", "Sergio", "Edward", "César", "Cristopher", "Daniel", "David", "Diego", "J.J", "Eduardo", "Emil", "Manuel", "Erik", "Ernesto", "Ethan", "Fabián", "Facundo", "Felipe", "Félix", "Hershel", "Fernando", "Francisco", "Taavi", "Gabriel", "Gaspar", "Paul", "Hugo", "Ian", "Iker", "Isaac", "Jacob", "Javier", "Jayden", "Jeremy", "Jerónimo", "Jesús", "Oleg", "Ned", "Joaquín", "Jorge", "Jorge  Alberto", "Ted", "José", "Cordell", "Jaime", "Patricio", "Fred", "George", "Harry", "Ronald", "Josh", "Niklaus", "Stefan", "Damián", "Damon", "Tyrese", "Tyler", "Tom", "Daryl", "Rick", "Álvaro", "Guillermo", "Julio", "Bryce", "Justin", "Kevin", "Lautaro", "Liam", "Lian", "Lorenzo", "Lucas", "Luis", "Albert", "Rudolph", "Gustavo", "Gustadolph", "Jamie", "Adán", "Mario", "Martín", "Mateo", "Matías", "Maximiliano", "Maykel", "Miguel", "Luigi", "Nelson", "Noah", "Oscar", "Pablo", "Pedro", "Rafael", "Ramón", "Raúl", "Ricardo", "Rigoberto", "Roberto", "Rolando", "Samuel", "Dean", "Santiago", "Santino", "Santos", "Sebastián", "Thiago", "Walter", "Tomás", "Valentino", "Vicente", "Víctor", "Sayid"];
	var lastname= ["Garcia", "Gonzalez", "Rodriguez", "Fernandez", "Lopez", "Martinez", "Sanchez", "Perez", "Gomez", "Martin", "Jimenez", "Ruiz", "Hernandez", "Diaz", "Moreno", "Alvarez", "Muñoz", "Romero", "Alonso", "Gutierrez", "Navarro", "Torres", "Dominguez",
	"Vazquez", "Ramos", "Gil", "Ramirez", "Serrano", "Blanco", "Suarez", "Molina", "Morales", "Ortega", "Delgado", "Castro", "Ortiz", "Rubio", "Marin", "Sanz", "Nuñez", "Iglesias", "Medina", "Garrido", "Santos", "Castillo", "Cortes", "Lozano", "Guerrero", "Cano", "Prieto", "Mendez", "Calvo", "Cruz", "Gallego", "Vidal", "Leon", "Herrera", "Marquez", "Peña", "Cabrera", "Flores", "Campos", "Vega", "Diez", "Fuentes", "Carrasco", "Caballero", "Nieto", "Reyes", "Aguilar", "Pascual", "Herrero", "Santana", "Lorenzo", "Hidalgo", "Montero", "Ibañez", "Gimenez", "Ferrer", "Duran", "Vicente", "Benitez", "Mora", "Santiago", "Arias", "Vargas", "Carmona", "Crespo", "Roman", "Pastor", "Soto", "Saez", "Velasco", "Soler", "Moya", "Esteban", "Parra", "Bravo", "Gallardo", "Rojas", "Pardo", "Merino", "Franco", "Espinosa", "Izquierdo", "Lara", "Rivas", "Silva", "Rivera", "Casado", "Arroyo", "Redondo", "Camacho", "Rey", "Vera", "Otero", "Luque", "Galan", "Montes", "Rios", "Sierra", "Segura", "Carrillo", "Marcos", "Marti", "Soriano", "Mendoza"];
    }else{
        firstname = ["Sandra", "Alice", "Caliandra", "Leah", "Alejandra", "Sarah", "Jimena", "Susan", "Laura", "Hannah", "Paloma", "Kisa", "Carla", "Beatrice", "Paula", "Lada", "Esther", "Monique", "Isaya", "Christine", "Daniela", "Kiara", "Carmen", "Gwendoline", "Edurne", "Emilia", "Manuela", "Erika", "Ramona", "Aura", "Adara", "Dulce", "Aliya", "Fiona","Bruna", "Frida", "Crésida", "Ginebra", "Dione", "Julieta", "Libia", "Kristen", "Shayla", "Lea", "Thais", "Magdalena", "Abril", "Saba", "Alexa", "Larisa", "Xia", "Mae", "Olaya", "Nadia", "Zoe", "Narel", "Tea", "Aine", "Alaia", "Camelia", "Martina", "Valeria", "Daniela", "Valentina", "Adriana", "Aitana", "Alexia", "Amanda", "Amina", "Camila", "Bianca", "Elena", "Carlota", "Mafalda", "Triana", "Esmeralda", "Marina", "Selene", "Greta", "Teresa", "Rebeca", "Ibbie", "Iris", "Jena", "Mara", "Mila", "Olivia", "Paris", "Alya", "Chloe", "Ariel", "Gala", "Dafne", "Haimi", "Cira", "Iana", "Eir", "Ivete", "Cora", "Claudia", "Kenya", "Ana", "Elda", "Tiberia", "Elba", "Zuri", "Hada", "Alida", "Elia", "Atenea", "Katia", "Cayetana", "Luz", "Dana", "Nélida", "Dánae", "Sira", "Diana", "Ofelia", "Lucía", "Sofía", "Julia", "Emma", "Alba", "Mía", "Ada"];
        lastname= ["Garcia", "Gonzalez", "Rodriguez", "Fernandez", "Lopez", "Martinez", "Sanchez", "Perez", "Gomez", "Martin", "Jimenez", "Ruiz", "Hernandez", "Diaz", "Moreno", "Alvarez", "Muñoz", "Romero", "Alonso", "Gutierrez", "Navarro", "Torres", "Dominguez",
        "Vazquez", "Ramos", "Gil", "Ramirez", "Serrano", "Blanco", "Suarez", "Molina", "Morales", "Ortega", "Delgado", "Castro", "Ortiz", "Rubio", "Marin", "Sanz", "Nuñez", "Iglesias", "Medina", "Garrido", "Santos", "Castillo", "Cortes", "Lozano", "Guerrero", "Cano", "Prieto", "Mendez", "Calvo", "Cruz", "Gallego", "Vidal", "Leon", "Herrera", "Marquez", "Peña", "Cabrera", "Flores", "Campos", "Vega", "Diez", "Fuentes", "Carrasco", "Caballero", "Nieto", "Reyes", "Aguilar", "Pascual", "Herrero", "Santana", "Lorenzo", "Hidalgo", "Montero", "Ibañez", "Gimenez", "Ferrer", "Duran", "Vicente", "Benitez", "Mora", "Santiago", "Arias", "Vargas", "Carmona", "Crespo", "Roman", "Pastor", "Soto", "Saez", "Velasco", "Soler", "Moya", "Esteban", "Parra", "Bravo", "Gallardo", "Rojas", "Pardo", "Merino", "Franco", "Espinosa", "Izquierdo", "Lara", "Rivas", "Silva", "Rivera", "Casado", "Arroyo", "Redondo", "Camacho", "Rey", "Vera", "Otero", "Luque", "Galan", "Montes", "Rios", "Sierra", "Segura", "Carrillo", "Marcos", "Marti", "Soriano", "Mendoza"]; 
    }
	var rand_first = Math.floor(Math.random()*firstname.length); 
	var rand_last = Math.floor(Math.random()*lastname.length);

    return [firstname[rand_first] + ' ' + lastname[rand_last], sex]
}   